version: "3"

services:
  n8n:
    image: n8nio/n8n
    # Bỏ --tunnel đi vì mình sẽ dùng URL từ ngrok
    command: start 
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - WEBHOOK_URL=https://vermiform-kandace-flabbergastedly.ngrok-free.dev
    dns:
      - 8.8.8.8
    volumes:
      - ./n8n_data:/home/node/.n8n